# Generated by Django 4.2.20 on 2025-03-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cuatrimestre', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VistaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_total', models.IntegerField()),
                ('tipo_texto', models.CharField(max_length=100)),
                ('textos_total', models.IntegerField()),
                ('puntaje_total', models.FloatField()),
                ('nivel_comprension_global', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionLecturaIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_texto', models.CharField(max_length=100)),
                ('titulo_lectura', models.CharField(max_length=200)),
                ('tipo_inferencia', models.CharField(max_length=100)),
                ('puntaje', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacionescl.registrousuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_texto', models.CharField(max_length=100)),
                ('textos_leidos', models.IntegerField()),
                ('porcentaje', models.FloatField()),
                ('nivel_comprension', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacionescl.registrousuarios')),
            ],
        ),
    ]
