# Generated by Django 4.2.20 on 2025-04-01 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionescl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='fecha_lectura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='fragmento',
            field=models.TextField(default='Fragmento no disponible'),
        ),
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='instruccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacionlecturaindividual',
            name='respuesta_usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionlecturaindividual',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionlecturaindividual',
            name='tipo_inferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionlecturaindividual',
            name='tipo_texto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluacionlecturaindividual',
            name='titulo_lectura',
            field=models.CharField(max_length=255),
        ),
    ]
